AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ebayGate:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
        paths:
          /data:
            post:
              responses: {}
        x-amazon-apigateway-cors:
          allowOrigins:
            - https://example.com
          allowHeaders:
            - Authorization
            - Content-Type
          allowMethods:
            - '*'
          exposeHeaders:
            - Content-Length
            - Content-Type
          allowCredentials: true