AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ebayGate:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
        paths:
          /data:
            post:
              responses: {}
        x-amazon-apigateway-cors:
          allowOrigins:
            - https://example.com
          allowHeaders:
            - Authorization
            - Content-Type
          allowMethods:
            - '*'
          exposeHeaders:
            - Content-Length
            - Content-Type
          allowCredentials: true
  reqsFromEbay:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-reqsFromEbay
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: reqsFromEbay
      CodeUri: src/reqsFromEbay
      Handler: handler.handler
      Runtime: python3.7
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref storedFromReqs
      Events:
        ebayGatePOSTdata:
          Type: HttpApi
          Properties:
            Path: /data
            Method: POST
            ApiId: !Ref ebayGate
      Environment:
        Variables:
          TABLE_NAME: !Ref storedFromReqs
          TABLE_ARN: !GetAtt storedFromReqs.Arn
  storedFromReqs:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-storedFromReqs
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)