AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
        paths:
          /price:
            post:
              responses: {}
        x-amazon-apigateway-cors:
          allowOrigins:
            - https://example.com
          allowHeaders:
            - Authorization
            - Content-Type
          allowCredentials: true
      Auth:
        DefaultAuthorizer: ''
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
        - preferred_username
      UserPoolName: !Sub ${AWS::StackName}-UserPool
  '?(@.Type === ''AWS::Serverless::HttpApi'')':
    Properties:
      Auth:
        Authorizers:
          '?(@.JwtConfiguration.audience[0].Ref === ''UserPoolClient'')':
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}